### ISSUE TITLE
v20190510生成时报Convert GBK to UTF8 failed, current encoding is GBK.但tars已经是utf8了，换成老版本tars2node(v20180713)能生成

### ISSUE THREAD

**Issue by liufee** [tars-node/tars2node#2]
v20190510生成时报Convert GBK to UTF8 failed, current encoding is GBK.但tars已经是utf8了，换成老版本tars2node(v20180713)能生成

**Comment by lihongchen** [comment]
遇到相同的问题

**Comment by liufee** [comment]
怎么不采用nodejs cli生成代码
php go版不都是用自身语言写的
...
